package mvcc

import (
	"github.com/ethereum/go-ethereum/common"
	"github.com/meta-node-blockchain/meta-node/types"
)

// MVCCSmartContractDB wraps the global SmartContractDB and the block's MVCC maps.
// It intercepts all storage reads/writes and event logs for a specific transaction (TxIndex).
// SCReadRecord records a read dependency for a transaction on smart contract storage
type SCReadRecord struct {
	Address common.Address
	Key     string
	Version Version
	WriteID WriteID
}

type MVCCSmartContractDB struct {
	baseDB       types.SmartContractDB
	storageMap   *MVCCStorageMap
	accountState types.AccountStateDB
	txIndex      Version

	// ReadSet tracks the storage slots read by this transaction
	ReadSet []SCReadRecord

	// WriteSet tracks the storage slots modified by this transaction.
	WriteSet []string
	
	// EventLogs buffers the logs generated by this transaction.
	EventLogs []types.EventLog
}

func NewMVCCSmartContractDB(baseDB types.SmartContractDB, storageMap *MVCCStorageMap, txIndex Version) *MVCCSmartContractDB {
	return &MVCCSmartContractDB{
		baseDB:     baseDB,
		storageMap: storageMap,
		txIndex:    Version(txIndex),
		ReadSet:    make([]SCReadRecord, 0, 8),
		WriteSet:   make([]string, 0, 8),
		EventLogs:  make([]types.EventLog, 0),
	}
}

func (db *MVCCSmartContractDB) markWrite(fullKey string) {
	for _, w := range db.WriteSet {
		if w == fullKey {
			return
		}
	}
	db.WriteSet = append(db.WriteSet, fullKey)
}

func (db *MVCCSmartContractDB) Code(address common.Address) []byte {
	// Code is immutable in most cases during execution, read directly from baseDB
	return db.baseDB.Code(address)
}

func (db *MVCCSmartContractDB) StorageValue(address common.Address, key []byte, customRoot ...*common.Hash) ([]byte, bool) {
	sKey := string(key)
	
	var val []byte
	var version Version
	var writeID WriteID
	var wakeup chan struct{}
	
	// Check MVCC map first
	for {
		val, version, writeID, wakeup = db.storageMap.Read(address, sKey, db.txIndex)
		if wakeup != nil {
			<-wakeup // SUSPEND: wait for estimating transaction
			continue
		}
		break
	}
	
	if val == nil {
		// Read from base DB if not found in MVCC
		baseVal, ok := db.baseDB.StorageValue(address, key, customRoot...)
		if ok {
			val = baseVal
		}
		version = BaseVersion
		writeID = BaseWriteID
	}

	// Record the read for validation phase
	fullKey := address.Hex() + sKey
	isWritten := false
	for _, w := range db.WriteSet {
		if w == fullKey {
			isWritten = true
			break
		}
	}
	if !isWritten {
		db.ReadSet = append(db.ReadSet, SCReadRecord{Address: address, Key: sKey, Version: version, WriteID: writeID})
		db.storageMap.AddReader(address, sKey, db.txIndex)
	}

	return val, val != nil
}

func (db *MVCCSmartContractDB) SetStorageValue(address common.Address, key []byte, value []byte) error {
	sKey := string(key)
	fullKey := address.Hex() + sKey
	
	// Write to MVCC map
	db.storageMap.Write(address, sKey, db.txIndex, value)
	db.markWrite(fullKey)
	
	return nil
}

func (db *MVCCSmartContractDB) BatchSetStorageValues(address common.Address, keys, values [][]byte) error {
	for i, key := range keys {
		if err := db.SetStorageValue(address, key, values[i]); err != nil {
			return err
		}
	}
	return nil
}

func (db *MVCCSmartContractDB) AddEventLogs(eventLogs []types.EventLog) {
	// Buffer event logs in RAM instead of writing directly
	db.EventLogs = append(db.EventLogs, eventLogs...)
}

func (db *MVCCSmartContractDB) SetAccountStateDB(asdb types.AccountStateDB) {
	db.accountState = asdb
}

func (db *MVCCSmartContractDB) SetBlockNumber(blockNumber uint64) {}
func (db *MVCCSmartContractDB) SetCode(address common.Address, codeHash common.Hash, code []byte) {}
func (db *MVCCSmartContractDB) StorageRoot(address common.Address, customRoot ...*common.Hash) common.Hash {
	return common.Hash{}
}
func (db *MVCCSmartContractDB) NewTrieStorage(address common.Address) common.Hash {
	return common.Hash{}
}
func (db *MVCCSmartContractDB) DeleteAddress(address common.Address) {}
func (db *MVCCSmartContractDB) GetSmartContractUpdateDatas() map[common.Address]types.SmartContractUpdateData {
	return nil
}
func (db *MVCCSmartContractDB) ClearSmartContractUpdateDatas() {}
