package mvcc

import (
	"github.com/ethereum/go-ethereum/common"
	"github.com/meta-node-blockchain/meta-node/types"
)

// MVCCSmartContractDB wraps the global SmartContractDB and the block's MVCC maps.
// It intercepts all storage reads/writes and event logs for a specific transaction (TxIndex).
type MVCCSmartContractDB struct {
	baseDB       types.SmartContractDB
	storageMap   *MVCCStorageMap
	accountState types.AccountStateDB
	txIndex      Version

	// ReadSet tracks the storage slots read by this transaction and their versions/writeIDs.
	// Map of storageKey -> read version
	ReadSet map[string]ReadVersion

	// WriteSet tracks the storage slots modified by this transaction.
	WriteSet map[string]bool
	
	// EventLogs buffers the logs generated by this transaction.
	EventLogs []types.EventLog

	BlockingVersion Version
}

func NewMVCCSmartContractDB(baseDB types.SmartContractDB, storageMap *MVCCStorageMap, txIndex Version) *MVCCSmartContractDB {
	return &MVCCSmartContractDB{
		baseDB:          baseDB,
		storageMap:      storageMap,
		txIndex:         Version(txIndex),
		ReadSet:         make(map[string]ReadVersion),
		WriteSet:        make(map[string]bool),
		EventLogs:       make([]types.EventLog, 0),
		BlockingVersion: BaseVersion,
	}
}

func (db *MVCCSmartContractDB) Code(address common.Address) []byte {
	// Code is immutable in most cases during execution, read directly from baseDB
	return db.baseDB.Code(address)
}

func (db *MVCCSmartContractDB) StorageValue(address common.Address, key []byte, customRoot ...*common.Hash) ([]byte, bool) {
	sKey := string(key)
	
	// Check MVCC map first
	val, version, writeID, blockingVer := db.storageMap.Read(address, sKey, db.txIndex)
	if blockingVer != BaseVersion {
		db.BlockingVersion = blockingVer
		// Return failure so the VM aborts execution immediately
		return nil, false
	}
	
	if val == nil {
		// Read from base DB if not found in MVCC
		baseVal, ok := db.baseDB.StorageValue(address, key, customRoot...)
		if ok {
			val = baseVal
		}
		version = BaseVersion
		writeID = BaseWriteID
	}

	// Record the read for validation phase
	fullKey := address.Hex() + sKey
	db.ReadSet[fullKey] = ReadVersion{Version: version, WriteID: writeID}

	return val, val != nil
}

func (db *MVCCSmartContractDB) SetStorageValue(address common.Address, key []byte, value []byte) error {
	sKey := string(key)
	fullKey := address.Hex() + sKey
	
	// Write to MVCC map
	db.storageMap.Write(address, sKey, db.txIndex, value)
	db.WriteSet[fullKey] = true
	
	return nil
}

func (db *MVCCSmartContractDB) BatchSetStorageValues(address common.Address, keys, values [][]byte) error {
	for i, key := range keys {
		if err := db.SetStorageValue(address, key, values[i]); err != nil {
			return err
		}
	}
	return nil
}

func (db *MVCCSmartContractDB) AddEventLogs(eventLogs []types.EventLog) {
	// Buffer event logs in RAM instead of writing directly
	db.EventLogs = append(db.EventLogs, eventLogs...)
}

func (db *MVCCSmartContractDB) SetAccountStateDB(asdb types.AccountStateDB) {
	db.accountState = asdb
}

func (db *MVCCSmartContractDB) SetBlockNumber(blockNumber uint64) {}
func (db *MVCCSmartContractDB) SetCode(address common.Address, codeHash common.Hash, code []byte) {}
func (db *MVCCSmartContractDB) StorageRoot(address common.Address, customRoot ...*common.Hash) common.Hash {
	return common.Hash{}
}
func (db *MVCCSmartContractDB) NewTrieStorage(address common.Address) common.Hash {
	return common.Hash{}
}
func (db *MVCCSmartContractDB) DeleteAddress(address common.Address) {}
func (db *MVCCSmartContractDB) GetSmartContractUpdateDatas() map[common.Address]types.SmartContractUpdateData {
	return nil
}
func (db *MVCCSmartContractDB) ClearSmartContractUpdateDatas() {}
