---
- name: Clean data and logs directories
  ansible.builtin.file:
    path: "{{ metanode_install_dir }}/node-{{ item[0] }}/{{ item[1] }}"
    state: absent
  loop: "{{ active_nodes | product(['data', 'logs']) | list }}"
