all:
  children:
    metanode_cluster:
      vars:
        ansible_user: "abc"
        ansible_ssh_pass: "1234@abcd"
        ansible_become_pass: "1234@abcd"
      hosts:
        192.168.1.230:
          node_ids: [3]
          is_synconly: true
        192.168.1.231:
          node_ids: [2]
        192.168.1.232:
          node_ids: [1]
        192.168.1.233:
          node_ids: [0]
