#!/bin/bash
# Start / stop / inspect the isolated account-gate E2E environment generated by gen_env.py.
# Only ever signals the processes whose PID this script recorded under BASE/pids — never a pattern or a port.
# Usage: run_env.sh <BASE> {start|stop|status}
set -u
BASE="$(cd "$1" && pwd)"; CMD="${2:-status}"
ENVJSON="$BASE/env.json"
j() { python3 -c "import json,sys; d=json.load(open('$ENVJSON')); print(eval(sys.argv[1]))" "$1"; }
BIN="$(j "d['bin']")"
PH="$(j "d['ports']['parent_http']")"
mkdir -p "$BASE/pids" "$BASE/logs"

wait_http() { for _ in $(seq 1 "${3:-90}"); do curl -s -m 2 "$1" -o /dev/null && return 0; sleep 1; done; echo "TIMEOUT waiting for $2" >&2; return 1; }
wait_rpc() { for _ in $(seq 1 "${2:-120}"); do
    r=$(curl -s -m 2 -X POST -H 'content-type: application/json' --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' "$1" 2>/dev/null)
    echo "$r" | grep -q '"result"' && return 0; sleep 1; done; echo "TIMEOUT waiting for RPC $1" >&2; return 1; }

start_exec() {
  local name="$1" rpc; rpc="$(j "d['ports']['$name']['rpc']")"
  local pprof_port=$((rpc - 200))
  local pprof_args=""
  if [ "${ENABLE_DEBUG_PPROF:-true}" = "true" ]; then
    pprof_args="-debug=true --pprof-addr=127.0.0.1:$pprof_port"
  fi
  ( cd "$BASE/$name" && \
    PARENT_CHAIN_URL="http://127.0.0.1:$PH" BLS_CONSERVATION_MODE=enforce BLS_CONSERVATION_INTERVAL_SECONDS=300 \
    exec "$BIN/simple_chain" $pprof_args -config="$BASE/$name/config.json" >>"$BASE/logs/$name.log" 2>&1 ) &
  echo $! >"$BASE/pids/$name.pid"
  wait_rpc "http://127.0.0.1:$rpc" 180 || { tail -20 "$BASE/logs/$name.log"; return 1; }
  echo "$name up (rpc :$rpc, pprof :$pprof_port, pid $(cat "$BASE/pids/$name.pid"))"
}

start_exec_async() {
  local name="$1" rpc; rpc="$(j "d['ports']['$name']['rpc']")"
  local pprof_port=$((rpc - 200))
  local pprof_args=""
  if [ "${ENABLE_DEBUG_PPROF:-true}" = "true" ]; then
    pprof_args="-debug=true --pprof-addr=127.0.0.1:$pprof_port"
  fi
  ( cd "$BASE/$name" && \
    PARENT_CHAIN_URL="http://127.0.0.1:$PH" BLS_CONSERVATION_MODE=enforce BLS_CONSERVATION_INTERVAL_SECONDS=300 \
    exec "$BIN/simple_chain" $pprof_args -config="$BASE/$name/config.json" >>"$BASE/logs/$name.log" 2>&1 ) &
  echo $! >"$BASE/pids/$name.pid"
}

wait_exec() {
  local name="$1" rpc; rpc="$(j "d['ports']['$name']['rpc']")"
  wait_rpc "http://127.0.0.1:$rpc" 180 || { tail -20 "$BASE/logs/$name.log"; return 1; }
  echo "$name up (rpc :$rpc, pid $(cat "$BASE/pids/$name.pid"))"
}

case "$CMD" in
  start)
    # `exec` inside the subshell makes $! the PID of the daemon itself (not of a wrapper), so stop signals the right process.
    ( cd "$BASE/parent" && exec "$BIN/parent_chain" -data-dir "$BASE/parent" -http ":$PH" \
        -rust-config "$BASE/parent/node_parent.toml" -genesis "$BASE/parent/parent_genesis.json" \
        >"$BASE/logs/parent.log" 2>&1 ) &
    echo $! >"$BASE/pids/parent.pid"
    wait_http "http://127.0.0.1:$PH/status" "parent" 120 || { tail -20 "$BASE/logs/parent.log"; exit 1; }
    echo "parent up (http :$PH, pid $(cat "$BASE/pids/parent.pid"))"
    MODE=$(j "d.get('mode', 'raft')")
    if [ "$MODE" = "mysticeti_4val" ]; then
      for v in val0 val1 val2 val3; do
        start_exec_async "$v"
        sleep 1
      done
      for v in val0 val1 val2 val3; do
        wait_exec "$v" || exit 1
      done
      if [ -d "$BASE/exec2" ]; then
        start_exec exec2 || exit 1
      fi
    else
      start_exec exec1 && sleep 3 && start_exec exec2
    fi ;;
  stop)
    for f in "$BASE"/pids/*.pid; do
      [ -f "$f" ] || continue
      n=$(basename "$f" .pid)
      [ "$n" = "parent" ] && continue
      pid=$(cat "$f")
      case "$(readlink -f /proc/$pid/exe 2>/dev/null)" in "$BIN"/*) ;; *) echo "$n: pid $pid is not ours any more, skipping"; rm -f "$f"; continue;; esac
      kill -TERM "$pid" 2>/dev/null
      for _ in $(seq 1 20); do kill -0 "$pid" 2>/dev/null || break; sleep 1; done
      kill -0 "$pid" 2>/dev/null && kill -KILL "$pid" 2>/dev/null
      rm -f "$f"; echo "$n stopped"
    done
    if [ -f "$BASE/pids/parent.pid" ]; then
      pid=$(cat "$BASE/pids/parent.pid")
      kill -TERM "$pid" 2>/dev/null
      for _ in $(seq 1 20); do kill -0 "$pid" 2>/dev/null || break; sleep 1; done
      kill -0 "$pid" 2>/dev/null && kill -KILL "$pid" 2>/dev/null
      rm -f "$BASE/pids/parent.pid"; echo "parent stopped"
    fi ;;
  stop_node)
    name="${3:-}"
    if [ -z "$name" ]; then echo "usage: $0 BASE stop_node <name>"; exit 1; fi
    f="$BASE/pids/$name.pid"
    if [ -f "$f" ]; then
      pid=$(cat "$f")
      kill -TERM "$pid" 2>/dev/null
      for _ in $(seq 1 20); do kill -0 "$pid" 2>/dev/null || break; sleep 1; done
      kill -0 "$pid" 2>/dev/null && kill -KILL "$pid" 2>/dev/null
      rm -f "$f"
      echo "$name stopped"
    fi ;;
  kill_node)
    name="${3:-}"
    if [ -z "$name" ]; then echo "usage: $0 BASE kill_node <name>"; exit 1; fi
    f="$BASE/pids/$name.pid"
    if [ -f "$f" ]; then
      pid=$(cat "$f")
      kill -KILL "$pid" 2>/dev/null
      rm -f "$f"
      echo "$name killed (SIGKILL)"
    fi ;;
  start_node)
    name="${3:-}"
    if [ -z "$name" ]; then echo "usage: $0 BASE start_node <name>"; exit 1; fi
    start_exec_async "$name"
    wait_exec "$name" || exit 1 ;;
  status)
    for f in "$BASE"/pids/*.pid; do
      [ -f "$f" ] || continue
      n=$(basename "$f" .pid)
      if kill -0 "$(cat "$f")" 2>/dev/null; then echo "$n: running (pid $(cat "$f"))"; else echo "$n: stopped"; fi
    done ;;
  *) echo "usage: $0 BASE {start|stop|status|start_node <name>|stop_node <name>|kill_node <name>}"; exit 1 ;;
esac
