// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: cross_chain_metadata.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CrossChainTransferMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: Target nation ID
	TargetNationId uint64 `protobuf:"varint,1,opt,name=target_nation_id,json=targetNationId,proto3" json:"target_nation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CrossChainTransferMetadata) Reset() {
	*x = CrossChainTransferMetadata{}
	mi := &file_cross_chain_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossChainTransferMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossChainTransferMetadata) ProtoMessage() {}

func (x *CrossChainTransferMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_cross_chain_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossChainTransferMetadata.ProtoReflect.Descriptor instead.
func (*CrossChainTransferMetadata) Descriptor() ([]byte, []int) {
	return file_cross_chain_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *CrossChainTransferMetadata) GetTargetNationId() uint64 {
	if x != nil {
		return x.TargetNationId
	}
	return 0
}

var File_cross_chain_metadata_proto protoreflect.FileDescriptor

const file_cross_chain_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1across_chain_metadata.proto\x12\vcross_chain\"F\n" +
	"\x1aCrossChainTransferMetadata\x12(\n" +
	"\x10target_nation_id\x18\x01 \x01(\x04R\x0etargetNationIdB3\n" +
	")com.meta_node.protos.compiled.cross_chainZ\x06/protob\x06proto3"

var (
	file_cross_chain_metadata_proto_rawDescOnce sync.Once
	file_cross_chain_metadata_proto_rawDescData []byte
)

func file_cross_chain_metadata_proto_rawDescGZIP() []byte {
	file_cross_chain_metadata_proto_rawDescOnce.Do(func() {
		file_cross_chain_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cross_chain_metadata_proto_rawDesc), len(file_cross_chain_metadata_proto_rawDesc)))
	})
	return file_cross_chain_metadata_proto_rawDescData
}

var file_cross_chain_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cross_chain_metadata_proto_goTypes = []any{
	(*CrossChainTransferMetadata)(nil), // 0: cross_chain.CrossChainTransferMetadata
}
var file_cross_chain_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cross_chain_metadata_proto_init() }
func file_cross_chain_metadata_proto_init() {
	if File_cross_chain_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cross_chain_metadata_proto_rawDesc), len(file_cross_chain_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cross_chain_metadata_proto_goTypes,
		DependencyIndexes: file_cross_chain_metadata_proto_depIdxs,
		MessageInfos:      file_cross_chain_metadata_proto_msgTypes,
	}.Build()
	File_cross_chain_metadata_proto = out.File
	file_cross_chain_metadata_proto_goTypes = nil
	file_cross_chain_metadata_proto_depIdxs = nil
}
