---
- name: Clean data and logs directories
  ansible.builtin.shell: |
    rm -rf "{{ metanode_install_dir }}/node-{{ item[0] }}/{{ item[1] }}"
  loop: "{{ active_nodes | product(['data', 'logs']) | list }}"
  failed_when: false
