// founding_entry generates a "founding_entry.json" for the Root Anchor genesis
// ceremony (Milestone D of note/cross_chain_root_anchor_architecture.md,
// section 1.3 #5 / 5.2.1 / 14 P1.2).
//
// This tool is meant to be run LOCALLY by each founding-chain operator, on the
// same machine (or an air-gapped copy) that already holds validator key
// material generated by `metanode keytool generate validator --out-dir <dir>`.
// No private key ever leaves the machine: this tool reads the keytool output,
// derives the min-pk (blst, G1) cross-chain committee key from the BLS secret
// scalar, signs a Proof-of-Possession, and writes ONLY public data.
//
// Usage:
//
//	founding_entry \
//	  --keys-dir ./node-0_keys --chain-id 101 --chain-name "Alpha Chain" \
//	  --hostname node-0 --ip 203.0.113.10 \
//	  --stake 1000000000000000000000 --out founding_entry.json
//
// See note/cross_chain_root_anchor_architecture.md and
// note/runbook_root_anchor_genesis_ceremony.md for the full ceremony
// (founding_entry.json -> assemble_root_anchor -> verify).
package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/meta-node-blockchain/meta-node/pkg/cross_chain/ceremony"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "founding_entry: error:", err)
		os.Exit(1)
	}
}

func run() error {
	keysDir := flag.String("keys-dir", "", "directory containing authority_key.json / protocol_key.json / network_key.json / eth_key.json produced by `metanode keytool generate validator`")
	chainID := flag.Uint64("chain-id", 0, "founding chain ID this validator belongs to (required)")
	chainName := flag.String("chain-name", "", "human-readable founding chain name (required)")
	hostname := flag.String("hostname", "", "validator hostname (required, must be unique across all founding chains)")
	ip := flag.String("ip", "127.0.0.1", "public IP/hostname this validator will be reachable at")
	p2pPort := flag.Int("p2p-port", 9100, "Rust consensus P2P port")
	primaryPort := flag.Int("primary-port", 6200, "Go P2P primary port")
	workerPort := flag.Int("worker-port", 4012, "Go worker port")
	description := flag.String("description", "", "validator description (default: \"Validator <hostname>\")")
	website := flag.String("website", "", "validator website")
	image := flag.String("image", "", "validator image URL")
	stake := flag.String("stake", "1000000000000000000000", "total staked amount in wei (decimal string)")
	minSelfDelegation := flag.String("min-self-delegation", "1000000000000000000", "minimum self-delegation in wei (decimal string)")
	commission := flag.Uint64("commission", 5, "commission rate")
	balance := flag.String("balance", "0", "initial native coin balance for this validator's genesis alloc entry, in wei")
	out := flag.String("out", "founding_entry.json", "output founding_entry.json path")
	flag.Parse()

	fe, err := ceremony.BuildFoundingEntry(ceremony.BuildFoundingEntryParams{
		KeysDir:           *keysDir,
		ChainID:           *chainID,
		ChainName:         *chainName,
		Hostname:          *hostname,
		IP:                *ip,
		P2PPort:           *p2pPort,
		PrimaryPort:       *primaryPort,
		WorkerPort:        *workerPort,
		Description:       *description,
		Website:           *website,
		Image:             *image,
		StakeWei:          *stake,
		MinSelfDelegation: *minSelfDelegation,
		Commission:        *commission,
		BalanceWei:        *balance,
	})
	if err != nil {
		return err
	}

	if err := ceremony.SaveFoundingEntry(*out, fe); err != nil {
		return fmt.Errorf("writing %s: %w", *out, err)
	}

	fmt.Printf("wrote %s (chain_id=%d hostname=%s eth_address=%s cross_chain_stake=%d)\n",
		*out, fe.ChainID, fe.GenesisValidator.Hostname, fe.GenesisValidator.Address, fe.CrossChain.Stake)
	fmt.Println("This file contains NO private key material and is safe to publish/share with the ceremony coordinator.")
	return nil
}
