all:
  vars:
    # URL RPC của Public Chain (Root Anchor Cluster)
    root_anchor_rpc: "http://[IP_ADDRESS]"
    ansible_user: "name"
    ansible_ssh_pass: "password"
    ansible_become_pass: "password"

  children:
    private_chains:
      hosts:
        # Máy 1 chạy Private Chain 101 tại /opt/metanode/chain-101
        server_201_chain_101:
          ansible_host: [IP_ADDRESS]
          chain_id: 101
          rpc_port: 8546
          port_offset: 10
          install_dir: "/opt/metanode/chain-101"

        # Máy 2 chạy Private Chain 102 tại /opt/metanode/chain-102
        server_202_chain_102:
          ansible_host: [IP_ADDRESS]
          chain_id: 102
          rpc_port: 8546
          port_offset: 20
          install_dir: "/opt/metanode/chain-102"
